Be/database update
Katherine-Damires/2021_Proyecto_Integrador_Equipo_4 pull request #100
Opened 2021-09-15 01:56 UTC by K-MoraPais

2021-09-15 13:56 UTC, JhonAires-Anima requested changes

2021-09-15 13:56 UTC, JhonAires-Anima commented on backend/anima-api/app/Http/Controllers/ControllerD.php
>              return "Donation stored successfully";
Maybe you should use `sendRequest()` and `sendError()` functions to have a more "professional" response.

2021-09-15 13:56 UTC, JhonAires-Anima commented on backend/anima-api/app/Http/Controllers/ControllerO.php
>          return $this->sendResponse($Ollas, '');
This sends automatically the response code?

2021-09-15 13:56 UTC, JhonAires-Anima commented on backend/anima-api/app/Http/Controllers/ControllerO.php
>          return $this->sendResponse($Ollas, '');
And maybe in the empty string you can add a Succesful message

2021-09-15 13:56 UTC, JhonAires-Anima commented on backend/anima-api/app/Models/User.php
> +    protected $primaryKey = "correo";
Why you change between single quotes and double quotes?

2021-09-15 13:56 UTC, JhonAires-Anima commented on backend/anima-api/app/Http/Controllers/ControllerU.php
>       */
Remember to clear all unnecesary comments

2021-09-16 00:46 UTC, K-MoraPais commented on backend/anima-api/app/Http/Controllers/ControllerD.php
>              return "Donation stored successfully";
Done

2021-09-16 00:49 UTC, K-MoraPais commented on backend/anima-api/app/Http/Controllers/ControllerO.php
>          return $this->sendResponse($Ollas, '');
I'm prioritizing login, registration and account activation tokens atm, so I'll resolve this later down the line.

2021-09-16 00:50 UTC, K-MoraPais commented on backend/anima-api/app/Models/User.php
> +    protected $primaryKey = "correo";
In some cases it is necessary, but not here. Resolved

2021-09-16 00:51 UTC, K-MoraPais commented on backend/anima-api/app/Http/Controllers/ControllerU.php
>       */
Laravel likes to add documentation stuff to autogenerated files, already deleted them. Resolved

2021-09-17 03:12 UTC, K-MoraPais commented on backend/anima-api/app/Http/Controllers/ControllerO.php
>          return $this->sendResponse($Ollas, '');
Done

2021-09-17 03:38 UTC, JhonAires-Anima requested changes

2021-09-17 03:38 UTC, JhonAires-Anima commented on backend/anima-api/.env
> +MAIL_FROM_NAME=Token_Kevin_Mora
You should change this to a name like "Ollas Populares"

2021-09-17 03:38 UTC, JhonAires-Anima commented on backend/anima-api/routes/api.php
> +Route::post('/donations/save', 'App\Http\Controllers\ControllerD@saveDonation');
You should add all the routes in the routes file.

2021-09-17 04:23 UTC, K-MoraPais commented on backend/anima-api/routes/api.php
> +Route::post('/donations/save', 'App\Http\Controllers\ControllerD@saveDonation');
I only add those that are finished, if they are not in the Routes.txt file, then they are not ready.

2021-09-17 04:24 UTC, K-MoraPais commented on backend/anima-api/.env
> +MAIL_FROM_NAME=Token_Kevin_Mora
Sure, i'll have it done tomorrow.

2021-09-18 18:32 UTC, braimor commented
Remember to manage the "Estado" field with a default value of "Con necesidad".

2021-09-19 20:16 UTC, K-MoraPais commented on backend/anima-api/.env
> +MAIL_FROM_NAME=Token_Kevin_Mora
Done

2021-09-19 21:00 UTC, JhonAires-Anima approved these changes

2021-09-19 21:12 UTC, merged