Feature/login
Katherine-Damires/2021_Proyecto_Integrador_Equipo_4 pull request #103
Opened 2021-09-17 21:48 UTC by JhonAires-Anima

Details:
- We create the Login functionality.

Notes:
- I commented some code to discuss if we eliminate it or not

2021-09-18 18:08 UTC, Kathy-Damires requested changes
me aparecen muchas cosas eliminadas en el css del registro

2021-09-18 18:08 UTC, Kathy-Damires commented on frontend/src/components/Register/Register.module.scss
> +    display: flex;
Eliminaste muchas cosas?

2021-09-18 18:08 UTC, Kathy-Damires commented on frontend/src/components/Register/Register.module.scss
> -        width: 55rem;
cambiaste los tamaños de los @medias en el header que es lo que cambia todos los tamaños del popup o solo lo eliminaste?

2021-09-18 18:20 UTC, JhonAires-Anima commented on frontend/src/App.jsx
> -};
Si, app fue eliminado para reestructurar la app, ya que es innecesario app cuando solo usa el router

2021-09-19 16:46 UTC, Kathy-Damires approved these changes

2021-09-19 20:51 UTC, merged