Ver mis ollas
Katherine-Damires/2021_Proyecto_Integrador_Equipo_4 pull request #114
Opened 2021-10-06 03:34 UTC by Katherine-Damires

add ver mis ollas con datos de prueba, responsive pero con dudas por la variacion de tamaño de la img segun el largo de la descripcion

galaxy fold
![image](https://user-images.githubusercontent.com/56731263/136136276-ca09835e-46cd-4167-8657-ee337d801715.png)
![image](https://user-images.githubusercontent.com/56731263/136136403-ad1fd787-b332-46b4-921a-75ee0d330bb5.png)

mobile
![image](https://user-images.githubusercontent.com/56731263/136136076-4130825b-e93b-4070-9c98-f9c78fa4c61a.png)

tablet 
![image](https://user-images.githubusercontent.com/56731263/136136472-42340e63-88ce-494d-b9ca-a69e10584029.png)

laptop > 1024
![image](https://user-images.githubusercontent.com/56731263/136136554-f599a463-a609-4384-b53d-c498180f2314.png)

1920:
![image](https://user-images.githubusercontent.com/56731263/136136627-96fb7e85-2809-49f4-9993-9683a5230900.png)

2021-10-07 21:27 UTC, JhonAires-Anima commented
Los botones para cambiar entre views no tienen la lupa y el texto a la misma altura. Y en el Galaxy Fold el botón de la derecha no se ve bien.

2021-10-07 21:37 UTC, JhonAires-Anima requested changes

2021-10-07 21:37 UTC, JhonAires-Anima commented on frontend/src/components/Management/VerMisOllas/VerMisOllas.module.scss
> +  border-radius: 16px;
```suggestion
  border-radius: 1rem;
```

2021-10-07 21:37 UTC, JhonAires-Anima commented on frontend/src/components/Management/VerMisOllas/VerMisOllas.module.scss
> +  border-radius: 16px;
Recordá que 16px = 1rem

2021-10-07 21:37 UTC, JhonAires-Anima commented on frontend/src/components/Management/VerMisOllas/VerMisOllas.module.scss
> +      width: 150px;
En tamaños tan grandes se usa rem

2021-10-07 21:37 UTC, JhonAires-Anima commented on frontend/src/components/Management/VerMisOllas/VerMisOllas.module.scss
> +      border-bottom-right-radius: 16px;
```suggestion
      border-top-right-radius: 1rem;
      border-bottom-right-radius: 1rem;
```

2021-10-07 21:37 UTC, JhonAires-Anima commented on frontend/src/components/Management/VerMisOllas/VerMisOllas.module.scss
> +        width: 160px;
usa rem

2021-10-07 21:37 UTC, JhonAires-Anima commented on frontend/src/components/Management/VerMisOllas/VerMisOllas.module.scss
> +      .state{
espacio entre clases

2021-10-07 21:37 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/index.jsx
> +  return (
espacio entre funciones con cualquier parte del código

2021-10-07 21:37 UTC, JhonAires-Anima commented on frontend/src/components/Management/VerMisOllas/VerMisOllas.module.scss
> +@import "../../../assets/styles/colors.module.scss";
en el codigo se está usando `'` no `"`, cambialo

2021-10-07 21:37 UTC, JhonAires-Anima commented on frontend/src/components/Management/VerMisOllas/index.jsx
> +import React from "react";
`'` a `"` en todo

2021-10-07 21:37 UTC, JhonAires-Anima commented on frontend/src/components/Management/VerMisOllas/index.jsx
> +import classes from "./VerMisOllas.module.scss";
espacio entre imports externos e internos

2021-10-07 21:56 UTC, Kathy-Damires commented
> Los botones para cambiar entre views no tienen la lupa y el texto a la misma altura. Y en el Galaxy Fold el botón de la derecha no se ve bien.

Entiendo que no se vea bien pero cuando elegis la segunda tab se corre y se ve completo. Lo otro lo reviso

2021-11-09 11:26 UTC, JhonAires-Anima requested changes

2021-11-09 11:26 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/index.jsx
> +                  value="1"
comillas dobles

2021-11-09 11:26 UTC, JhonAires-Anima commented on frontend/src/components/ViewMy/ViewMyDonations/index.jsx
> +import React from "react";
comillas dobles

2021-11-09 11:26 UTC, JhonAires-Anima commented on frontend/src/components/ViewMy/ViewMyPots/NotFound/NotFound.module.scss
> +@import "../../../../assets/styles/colors.module.scss";
comillas dobles

2021-11-09 11:26 UTC, JhonAires-Anima commented on frontend/src/components/ViewMy/ViewMyPots/NotFound/index.jsx
> +import React, { useState } from "react";
comillas dobles

2021-11-09 11:26 UTC, JhonAires-Anima commented on frontend/src/components/ViewMy/ViewMyPots/ViewMyPots.module.scss
> +@import "../../../assets/styles/colors.module.scss";
comillas dobles

2021-11-09 11:26 UTC, JhonAires-Anima commented on frontend/src/components/ViewMy/ViewMyPots/NotFound/index.jsx
> +export default NotFound;
falta linea al final del archivo

2021-11-09 11:26 UTC, JhonAires-Anima commented on frontend/src/components/ViewMy/ViewMyPots/index.jsx
> +import React, { useState, useEffect } from "react";
comillas dobles

2021-11-09 11:26 UTC, JhonAires-Anima commented on frontend/src/router/index.jsx
> +import React from "react";
comillas dobles

2021-11-09 11:26 UTC, JhonAires-Anima commented on frontend/src/components/Layout/Header/index.jsx
> +    window.location.href='/view-my'
Deberías cambiar esto por history.push().
Adjunto link a [documentación](https://v5.reactrouter.com/web/api/Hooks/usehistory)

2021-11-09 12:29 UTC, JhonAires-Anima requested changes

2021-11-09 12:29 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CreatePots/index.jsx
>              id: "address",
comillas dobles

2021-11-09 12:29 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/Ollas.module.scss
> +  background-color: #ffffff;
archivo de colores

2021-11-09 12:29 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/Ollas.module.scss
> +    color: #bd3131;
archivo de colores

2021-11-09 12:29 UTC, JhonAires-Anima commented on frontend/src/components/ViewMy/ViewMyPots/ViewMyPots.module.scss
> +    border: 1px solid #dcdcdc;
archivo de colores

2021-11-09 12:29 UTC, JhonAires-Anima commented on frontend/src/components/ViewMy/ViewMyPots/ViewMyPots.module.scss
> +    border: 2px solid #000;
archivo de colores

2021-11-09 12:29 UTC, JhonAires-Anima commented on frontend/src/pages/ViewMy/ViewMy.module.scss
> +        color: #bd3131;
archivo de colores

2021-11-09 15:22 UTC, JhonAires-Anima approved these changes

2021-11-09 15:31 UTC, merged