Fixes
Katherine-Damires/2021_Proyecto_Integrador_Equipo_4 pull request #118
Opened 2021-10-08 14:24 UTC by Kathy-Damires

Detalles:
- elimine los "only screen"
- Cambie los nombres de las carpetas de buscar y crear ollas a ingles
- Cambie todas las clases a ingles en buscar y crear ollas y home
- Agregue el places autocomplete input
- Agregue para que se guarden las coordenadas según la direccion ingresada
- Agregue el file uploader para agregar imagenes
- Cambie el fetch controller en add_pots para que se mande bien la imagen con formData

![image](https://user-images.githubusercontent.com/56731263/140421096-12bb951d-9af5-4298-8296-bb08655f3175.png)

2021-10-10 21:48 UTC, JhonAires-Anima commented
En un pull request deberías solo poner las cosas que hiciste además de cierto "profesionalismo". Esto sin importar si se hablo antes con el reviewer.

2021-10-10 21:53 UTC, JhonAires-Anima requested changes

2021-10-10 21:53 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/index.jsx
> +} from "@material-ui/icons/";
usá `'` en vez de `"`

2021-10-10 21:53 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/index.jsx
> +        <button className={classes["agregar-button"]} type="submit">
cambiá todas las comillas

2021-10-14 00:49 UTC, JhonAires-Anima requested changes

2021-10-14 00:49 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/BuscarOllas/BuscarOllas.module.scss
> +@media only screen and (max-width: 426px) and (min-width: 280px) {
```suggestion
@media (max-width: 426px) and (min-width: 280px) {
```

2021-10-14 00:49 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/CrearOllas.module.scss
> +@media only screen and (max-width: 520px) and (min-width: 280px) {
```suggestion
@media (max-width: 520px) and (min-width: 280px) {
```

2021-10-14 00:49 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/CrearOllas.module.scss
> +@media (max-width: 730px) and (min-width: 520px) {
```suggestion
@media (max-width: 768px) and (min-width: 520px) {
```

2021-10-17 00:59 UTC, JhonAires-Anima requested changes

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/BuscarOllas/BuscarOllas.module.scss
> +@media only screen and (max-width: 426px) and (min-width: 280px) {
```suggestion
@media (max-width: 426px) and (min-width: 280px) {
```

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/BuscarOllas/BuscarOllas.module.scss
> +    padding: 6%;
No es recomendable usar porcentajes en paddings ni margins, sin mencionar que usas porcentajes de manera excesiva, por lo que es mucho más fácil que las cosas se rompan debido al tamaño de la pantalla. Ej: Si una persona está en celular y decide girar la pantalla en la página posiblemente la página se romperá al no ser un caso previsto y usar tantos porcentajes en vez de valores fijos según el tamaño de pantalla.

No digo que lo cambies, pero tenélo en cuenta para futuros diseños.

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/CrearOllas.module.scss
> +  .horarios-and-button {
Por qué cambias entre código en español e inglés? 

Si tenés dudas de cómo se escribe una palabra en ingles lo podes buscar en google, las posibles traducciones de horarios según el traductor de google son: schedule, hour hand y timetable. En este caso la traducción más correcta me parecería schedule.

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/CrearOllas.module.scss
> +@media only screen and (max-width: 520px) and (min-width: 280px) {
```suggestion
@media and (max-width: 520px) and (min-width: 280px) {
```

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/CrearOllas.module.scss
> +    .horarios-and-button {
español e inglés

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/CrearOllas.module.scss
> +@media only screen and (max-width: 1024px) and (min-width: 731px) {
```suggestion
@media (max-width: 1024px) and (min-width: 731px) {
```

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/CrearOllas.module.scss
> +    .horarios-and-button {
español e inglés

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/CrearOllas.module.scss
> +    .horarios-and-button {
español e inglés

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/index.jsx
> +                maxLength='2'
Estás usando mal estas propiedades, ya que `maxLength` no aplica para inputs de tipo número y `min` y `max` no tienen ese uso. Adjunto [documentación](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-maxlength) y una publicación de [stack overflow](https://stackoverflow.com/questions/18510845/maxlength-ignored-for-input-type-number-in-chrome) para que puedas ver a qué me refiero.

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/index.jsx
> +                ref={toTimeFirstInputRef}
Recomiendo ver `useState` para mantener el estado actual de inputs y no tener que usar tantos `useRef`, sin mencionar que esto va a ser cambiado a esta forma después del refactor. Dejo un [ejemplo](https://dirask.com/posts/React-update-useState-object-properties-with-input-jvo231) para que te puedas guiar

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/pages/Home/Home.module.scss
> +@media only screen and (max-width: 1500px) and (min-width: 1100px) {
```suggestion
@media (max-width: 1500px) and (min-width: 1100px) {
```

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/pages/Home/Home.module.scss
>      .img-container {
espacio entre clases

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/pages/Home/Home.module.scss
> +@media only screen and (max-width: 1920px) and (min-width: 1501px) {
```suggestion
@media (max-width: 1920px) and (min-width: 1501px) {
```

2021-10-17 00:59 UTC, JhonAires-Anima commented on frontend/src/pages/Home/Home.module.scss
> +@media only screen and (min-width: 1921px) {
```suggestion
@media (min-width: 1921px) {
```

2021-10-17 16:27 UTC, Kathy-Damires commented on frontend/src/components/Ollas/BuscarOllas/BuscarOllas.module.scss
> +    padding: 6%;
Dale :)

2021-10-17 20:56 UTC, JhonAires-Anima commented on frontend/src/components/Ollas/CrearOllas/index.jsx
> +                ref={toTimeFirstInputRef}
Aunque sigue utilizando `useRef` quería que tomes en cuenta el uso de `useState` para mantener el tracking de un input.

Y si tenés dudas de cómo se haría sin useRef una aproximación sería:

```
const handleInsert = (event) => {
    const newPropertyKey = event.target.id;
    const newPropertyValue = event.target.value;
    setUser({ ...user, [newPropertyKey]: newPropertyValue });
  };
```

2021-10-19 12:05 UTC, Kathy-Damires commented on frontend/src/components/Ollas/CrearOllas/index.jsx
> +                maxLength='2'
Si queres hacer refactor, hacelo pero recorda que esas propiedades las habias agregado vos

2021-10-19 12:06 UTC, Kathy-Damires commented on frontend/src/components/Ollas/CrearOllas/index.jsx
> +                ref={toTimeFirstInputRef}
Si queres hacer refactor, hacelo pero recorda que esas propiedades las habias agregado vos y yo aun no me familiarizo con como funcionan lo useRef y useState

2021-11-01 21:26 UTC, Kathy-Damires commented on frontend/src/components/Ollas/CreatePots/CreatePots.module.scss
> +    .schedule-and-button {
los pongo por que a veces no me los toma si no le pongo la clase en la que esta adentro

2021-11-05 22:51 UTC, closed without merging