Login
Katherine-Damires/2021_Proyecto_Integrador_Equipo_4 pull request #94
Opened 2021-09-01 15:44 UTC by Alex-Torres333

Revísalo

2021-09-01 23:14 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.jsx
> +    <div className={classes.modal}>
Si la clase modal no tiene ningún estilo es innecesaria.

2021-09-01 23:17 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.jsx
> +        </a>
Por el momento esto está bien, pero en un futuro va a ser cambiado por el elemento <Link> de react-router-dom, ya que da problemas al querer cambiar de página usando React.

2021-09-01 23:29 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.jsx
> +      <div className={classes.InfoContainer}>
Ya que al darle al boton para logearse va a enviar una request al backend y hay distintos inputs, por convención este elemento debería ser un `<form>`  además de tener las propiedes `onSubmit` llamando a la función destinada a hacer la request `loginHandler`, la propiedad `onSubmit` llama a el elemento que tenga la propiedad `type="submit"` el cual es un botón usualmente.

2021-09-01 23:32 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +  background-color: white;
Los colores deberían ser en código HEX `#ffffff`

2021-09-01 23:32 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +  box-shadow: 0px 5px 10px rgba(114, 187, 219, 0.26), 0px 20px 40px rgba(114, 187, 219, 0.29);
Lo mismo que mencioné antes.

2021-09-01 23:36 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +  padding: 14px 24px;
En `margin` y `padding` los pixeles deberían ser cambiados por `rem`, `16px = 1rem`, hay varios convertores de px a rem y viceversa.

2021-09-01 23:37 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.jsx
> +        <button>Entrar</button>
Al cambiar el div padre a form tendrías que poner la propiedad `type="submit"`

2021-09-01 23:42 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +      font-weight: bold;
No suele ser recomendable usar cosas como `bold`, ya que el tamaño de la letra puede variar según el navegador, la pc, etc. Se recomienda usar propiedades iguales en todos los sistemas como `px` o `rem` en nuestro caso.

2021-09-01 23:44 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +      height: 40px;
Recomiendo cambiar esto y todo lo que tenga `px` a `rem` para tener un estándar.

2021-09-01 23:46 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +@media (max-width: 425px) {
En el caso de los tamaños mantenelo en px.

Recomiendo usar `min-width` o `max-width` durante todo el documento pero no los dos, ya que esto puede causar inconvenientes.

2021-09-01 23:47 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +@media (min-width: 1920px) {
Lo mismo que antes, se recomienda usar uno de los 2, pero no los 2.

2021-09-01 23:51 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +  .modal {
Si ya llamaste al elemento arriba no es necesario llamarlo de nuevo, recordá que estás usando `scss` no `css`.

2021-09-01 23:53 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.jsx
> +const Login = () => (
Un espacio entre los imports y la función no mata a nadie. 😊

2021-09-02 10:45 UTC, Alex-Torres333 commented on frontend/src/index.jsx
> +      <Login />
Lo quito directamente entonces?

2021-09-02 11:01 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.module.scss
> +.LoginBtn {
Ya esta arreglado

2021-09-02 11:20 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.jsx
> +        <p>Bienvenido</p>
Ya lo cambie a un h2

2021-09-02 12:04 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.module.scss
> +@media (max-width: 425px) {
Ya esta arreglado, pero que conste que fueron más complicaciones para usar uno solo

2021-09-02 12:18 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.module.scss
> +  .modal {
okey

2021-09-02 14:03 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +      height: 40px;
Hay ciertos navegadores que no escalan bien los pixeles al hacer zoom.

2021-09-02 14:43 UTC, JhonAires-Anima requested changes

2021-09-03 11:24 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.module.scss
> +  box-shadow: 0rem 0.313rem 0.625rem rgba(114, 187, 219, 0.26), 0px 1.25rem 2.5rem rgba(114, 187, 219, 0.29);
Ahora si estan todos

2021-09-03 11:24 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.module.scss
> +  background-color: white;
Ya esta

2021-09-03 12:08 UTC, JhonAires-Anima requested changes

2021-09-03 12:08 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.jsx
>          <input type='password' placeholder="Contraseña"></input>
Deberías agregar un mínimo de caracteres para aceptar el submit, y en caso de que no sean validos los 2 inputs debe enviar un mensaje de error, recomiendo ver useState().

2021-09-03 12:08 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +  box-shadow: 0rem 0.313rem 0.625rem #72bcdb31, 0px 1.25rem 2.5rem #72bcdb27;
Si un valor es 0 no importa si es px o rem

2021-09-03 12:08 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
>      font-weight: bold;
Es mejor cambiar el tamaño a un número, ya que dependiendo el navegador puede variar el tamaño.

2021-09-03 12:11 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.jsx
>          <input type='password' placeholder="Contraseña"></input>
Estaba seguro de haber leído esto ya en el anterior pero no lo encontré cuando revisé

2021-09-03 12:14 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.module.scss
>      font-weight: bold;
No entendí

2021-09-03 12:15 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.module.scss
> +  box-shadow: 0rem 0.313rem 0.625rem #72bcdb31, 0px 1.25rem 2.5rem #72bcdb27;
Y entonces?

2021-09-06 11:33 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +  box-shadow: 0rem 0.313rem 0.625rem #72bcdb31, 0px 1.25rem 2.5rem #72bcdb27;
Se deja en 0

2021-09-06 11:34 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
>      font-weight: bold;
en vez de bold utilizar un numero del 100 al 900

2021-09-06 12:17 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.module.scss
>      font-weight: bold;
ya esta

2021-09-06 12:17 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.module.scss
> +  box-shadow: 0rem 0.313rem 0.625rem #72bcdb31, 0px 1.25rem 2.5rem #72bcdb27;
bueno

2021-09-06 14:05 UTC, JhonAires-Anima requested changes

2021-09-06 14:09 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.module.scss
> +  box-shadow: 0rem 0.313rem 0.625rem #72bcdb31, 0px 1.25rem 2.5rem #72bcdb27;
No entiendo exactamente que debo solucionar ahí

2021-09-06 14:09 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.jsx
> +        <input type='password' placeholder="Contraseña" minLength='8' required='required'></input>
Supongo que esto es por las comillas dobles

2021-09-06 14:14 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.jsx
> +const Login = () => (
Por?

2021-09-06 14:16 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.jsx
> +const Login = () => (
Porque así tiene que ser estructurado

2021-09-06 14:17 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.jsx
> +        <input type='password' placeholder="Contraseña" minLength='8' required='required'></input>
No, va sin `='required'` solo required

2021-09-06 14:17 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login.module.scss
> +  box-shadow: 0rem 0.313rem 0.625rem #72bcdb31, 0px 1.25rem 2.5rem #72bcdb27;
poner lo que sea 0 en 0 y no decir el tipo de medida

2021-09-06 14:18 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.jsx
> +        <input type='password' placeholder="Contraseña" minLength='8' required='required'></input>
Ah okey

2021-09-06 14:18 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.jsx
> +const Login = () => (
Okey, ya lo muevo

2021-09-06 14:39 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login.module.scss
> +  box-shadow: 0rem 0.313rem 0.625rem #72bcdb31, 0px 1.25rem 2.5rem #72bcdb27;
Ya esta

2021-09-06 19:18 UTC, JhonAires-Anima requested changes

2021-09-06 19:28 UTC, JhonAires-Anima requested changes

2021-09-06 19:28 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login/Login.module.scss
> +    margin: 1.5rem, 1.5rem;
El margin me parece muy excesivo y más que nada en mobile

2021-09-06 19:28 UTC, JhonAires-Anima commented on frontend/src/index.jsx
> +//import Login from './components/UI/Login/Login.jsx';
Este comment es innecesario

2021-09-06 19:28 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login/Login.jsx
> +          href="https://www.google.com/?hl=es" //Lo dejé como Google porque no se exactamente que irá ahi
El comment nunca va para este tipo de casos, y el `href` si no se sabe la dirección se direcciona a la misma página en la que se encuentra

2021-09-06 19:51 UTC, Alex-Torres333 commented on frontend/src/index.jsx
> +//import Login from './components/UI/Login/Login.jsx';
Lo deje por si tenía que volver a activar el proyecto, ya que sin esa ruta no puedo correrlo.
Cuando este listo para el merge haré un ultimo commit en el que lo quite

2021-09-06 19:51 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login/Login.jsx
> +          href="https://www.google.com/?hl=es" //Lo dejé como Google porque no se exactamente que irá ahi
Ya lo cambio

2021-09-06 19:52 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login/Login.module.scss
> +    margin: 1.5rem, 1.5rem;
Pues a mi me parece perfecto, y por eso lo deje así

2021-09-07 12:02 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login/Login.module.scss
> +    margin: 1.5rem, 1.5rem;
Es innegable que en mobile es demasiado grande al tener las mismas medidas que tiene en desktop

2021-09-07 12:03 UTC, JhonAires-Anima commented on frontend/src/index.jsx
> +//import Login from './components/UI/Login/Login.jsx';
El commit que pusheas siempre tiene que ser el último a menos que te digan lo contrario en el code review

2021-09-07 12:08 UTC, Alex-Torres333 commented on frontend/src/index.jsx
> +//import Login from './components/UI/Login/Login.jsx';
Me resulta poco viable tener que escribir la ruta de nuevo cada que vaya a iniciar el proyecto de nuevo pero okey

2021-09-07 12:09 UTC, Alex-Torres333 commented on frontend/src/index.jsx
> +//import Login from './components/UI/Login/Login.jsx';
Tiene sentido

2021-09-07 12:18 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login/Login.module.scss
> +    margin: 1.5rem, 1.5rem;
El punto no es compararlas entre el desktop y el mobile, si se ve bien en ambas plataformas no importa que sean las mismas medidas.
Lo estoy viendo usando el f12 (no recuerdo el nombre de la herrmienta) y siendo un popup que lo usas y se cierra se ve bien

2021-09-07 12:18 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login/Login.module.scss
> +    margin: 1.5rem, 1.5rem;
Ademas no es por el margin, esa propiedad la esta contando como invalida, la quite y no hay diferencia

2021-09-13 19:29 UTC, JhonAires-Anima requested changes

2021-09-13 19:29 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login/Login.module.scss
> +
Es innecesario volver a mencionar esto ya que fue aplicado en la anterior medida.

2021-09-13 19:29 UTC, JhonAires-Anima commented on frontend/src/components/UI/Login/Login.module.scss
> +  background: rgba(0, 0, 0, 0.5);
Usá codigo `HEX` para poner los colores

2021-09-16 01:02 UTC, Katherine-Damires requested changes

2021-09-16 01:02 UTC, Katherine-Damires commented on frontend/src/components/UI/Login/Login.jsx
> +        <p>Contraseña</p>
Deberías poner los <p> que están sobre los inputs como labels

2021-09-16 10:55 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login/Login.module.scss
> +
No lo habia notado, ya lo quito

2021-09-16 10:55 UTC, Alex-Torres333 commented on frontend/src/components/UI/Login/Login.module.scss
> +  background: rgba(0, 0, 0, 0.5);
Es vdd

2021-09-16 16:03 UTC, JhonAires-Anima approved these changes

2021-09-16 23:13 UTC, merged