Registro
Katherine-Damires/2021_Proyecto_Integrador_Equipo_4 pull request #95
Opened 2021-09-02 11:58 UTC by Katherine-Damires

- Realice los cambios sugeridos
- Es responsive
- No tiene funcionalidad pero ya se le puede implementar 

popup  > 1920 width 60hz screen size
![image](https://user-images.githubusercontent.com/56731263/133176980-0aee4fc0-d3ba-4120-882e-d7563bb8f1a1.png)

popup  < 1920,  > 1024 width laptop size
![image](https://user-images.githubusercontent.com/56731263/133177062-5e91bc40-4086-41c2-b55c-3af5bd733efc.png)

popup in < 1024 width tablet size
![image](https://user-images.githubusercontent.com/56731263/133177351-87a90920-5751-4e74-9018-a53f36d2a84a.png)

popup in  < 425  width mobile size
![image](https://user-images.githubusercontent.com/56731263/133177654-77645410-28ee-48df-8349-d79c4803012a.png)

galaxy fold
![image](https://user-images.githubusercontent.com/56731263/133177838-67544922-3b78-4824-8a2b-5305fa5bc302.png)

2021-09-02 15:17 UTC, JhonAires-Anima requested changes

2021-09-02 15:17 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +  font-size: 18px;
Cosas como tamaños, margin, padding deberían ser `rem` en vez de `px` `1rem` = `16px`

2021-09-02 15:17 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +  background-color: white;
```suggestion
  background-color: #ffffff;
```

2021-09-02 15:17 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +      width: 709px;
Siempre que se quiera usar `px` es recomendable usar `rem` a menos que sea algo muy minúsculo.

2021-09-02 15:17 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +      button {
Agrega espacios entre finales de clases e inicios

2021-09-02 15:17 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +}
esto puede ir dentro de la clase `modal` y no es necesario mencionarla.

2021-09-02 15:17 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +.modal {
Si no tiene ningún estilo la clase es innecesaria.

2021-09-02 15:17 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +        color: white;
```suggestion
        color: #ffffff;
```

2021-09-08 16:38 UTC, Katherine-Damires commented on frontend/src/components/UI/Registro.jsx
> +            <input type="password" placeholder="Confirmar Contraseña" id="confirmarCotrasenia" value onChange={(e) => setConfirmarContrasenia(e.target.vaule)} />
Lo se hacer pero utilizando el state y set state y no recuerdo si se puede usar ya que lo haciamos antes asi con a alnterios version de react.
Algo asi: 

if (this.state.Password.length < 8) {
                    this.setState({
                        PasswordError: 'La contraseña ingresada es menor a 8 caracteres.'
                    })

2021-09-08 16:41 UTC, Katherine-Damires commented on frontend/src/components/UI/Registro.jsx
> +            <input type="password" placeholder="Confirmar Contraseña" id="confirmarCotrasenia" value onChange={(e) => setConfirmarContrasenia(e.target.vaule)} />
sino lo dejo como esta y se lo agregas vos de la forma que creas correcta

2021-09-08 16:48 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.jsx
> +            <input type="password" placeholder="Confirmar Contraseña" id="confirmarCotrasenia" value onChange={(e) => setConfirmarContrasenia(e.target.vaule)} />
en html hay una propiedad llamada minlength

2021-09-08 17:49 UTC, Katherine-Damires commented on frontend/src/components/UI/Registro.module.scss
> +      width: 709px;
Al realizar el cambio de px a rem en los inputs y el boton me empezo a romper el responsive en todas las medidas que antes estaban bien
![image](https://user-images.githubusercontent.com/56731263/132559122-0b4cde86-b255-4baf-8390-0e130795116b.png)

2021-09-08 17:59 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +      width: 709px;
1rem = 16px, hay convertores de px a rem

2021-09-08 22:28 UTC, JhonAires-Anima commented
No pusiste la imagen en mobile, y me acabo de dar cuenta que el componente está en UI, deberías mover el componente junto al estilo a components/Login/

2021-09-08 22:42 UTC, JhonAires-Anima requested changes

2021-09-08 22:42 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.jsx
> +            <button type="submit">Registrarse</button>
se debería agregar una advertencia si la contraseña no es igual, recomiendo usar `useRef()` si necesitas ayuda en eso avisame.

2021-09-08 22:42 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.jsx
> +  const handlesubmit = () => {
```suggestion
  const submitHandler = () => {
```

2021-09-08 22:42 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +}
Agregá una linea al final

2021-09-08 22:42 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +        input {
hace separaciones entre elementos

2021-09-08 22:42 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +    box-shadow: 0px 5px 10px rgba(114, 187, 219, 0.26), 0px 20px 40px rgba(114, 187, 219, 0.29);
Los colores tienen que ser en código `HEX`, además que si un valor es 0 no importa el tipo de medida, es decir: 0px => 0

2021-09-08 22:42 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.module.scss
> +        font-size: 40px;
Para valores mayores a `10px` usá `rem`

2021-09-08 23:59 UTC, Katherine-Damires commented on frontend/src/components/UI/Registro.module.scss
> +    box-shadow: 0px 5px 10px rgba(114, 187, 219, 0.26), 0px 20px 40px rgba(114, 187, 219, 0.29);
No lo cambio por que son del botón del header que esta en el header que vos creaste por lo que lo voy a sacar una vez que termine de trabajar con el popup

2021-09-09 15:38 UTC, Katherine-Damires commented on frontend/src/components/UI/Registro.jsx
> +            <button type="submit">Registrarse</button>
Help!

2021-09-11 20:08 UTC, Katherine-Damires commented on frontend/src/components/UI/Registro.jsx
> +            <button type="submit">Registrarse</button>
encontre un ejemplo pero que es el que mas entendi pero usa react hook form 
https://codesandbox.io/s/react-hook-form-password-match-check-standard-validation-eo6en?file=/src/index.js
si quere implementalo vos con la funcionalidad

2021-09-13 16:34 UTC, JhonAires-Anima commented on frontend/src/components/UI/Registro.jsx
> +            <button type="submit">Registrarse</button>
useForm es un custom hook, no algo de react nativo, si queres que sea implementado sos libre de hacerlo.

2021-09-13 18:51 UTC, JhonAires-Anima requested changes

2021-09-13 18:51 UTC, JhonAires-Anima commented on frontend/src/components/Login/Register.module.scss
> +.registerButton {
En vez de usar camel case en css se suele usar kebab case, para hacer referencia a una clase de este estilo se hace así:
<elemento className={classes['element-class']}>(si es una clase con guión separador, de lo contrario se mantiene como antes)

2021-09-13 18:51 UTC, JhonAires-Anima commented on frontend/src/components/Login/Register.module.scss
> +        }
En vez de llamar a los elementos hijos directamente es mucho mejor usar clases en todos, por temas de rendimiento y de entendimiento, ya que es mucho más entendible un `.register-button` a un `button`

2021-09-13 18:51 UTC, JhonAires-Anima commented on frontend/src/components/Login/Register.jsx
> +      {close => (
Para qué es esto?

2021-09-13 18:51 UTC, JhonAires-Anima commented on frontend/src/components/Login/Register.jsx
> +  };
esta función debería tener un event.preventHandler();

2021-09-13 18:51 UTC, JhonAires-Anima commented on frontend/src/components/Login/Register.module.scss
> +position: absolute;
no es recomendable usar absolute a menos que no hay a otra solución, y en el caso del botón puesto como está hay otras a mi punto de vista

2021-09-13 18:54 UTC, JhonAires-Anima commented on frontend/src/components/Login/Register.jsx
> +            <a href="http://">Ya tienes cuenta? Inicia sesión</a>
Me parece que el `<a>` solo debería envolver el Inicia sesión y el ya tienes cuenta? sería ¿Ya tienes cuenta?

2021-09-13 23:07 UTC, Katherine-Damires commented on frontend/src/components/Login/Register.jsx
> +      {close => (
Para abrir el popup al presionar el boton

2021-09-13 23:07 UTC, Katherine-Damires commented on frontend/src/components/Login/Register.jsx
> +      {close => (
y si la pregunta es por el close, es para que funcione el boton de cerrar

2021-09-13 23:09 UTC, Katherine-Damires commented on frontend/src/components/Login/Register.jsx
> +  };
Unexpected use of 'event'  no-restricted-globals
 por esta razon no lo pongo

2021-09-13 23:26 UTC, Katherine-Damires commented on frontend/src/components/Login/Register.module.scss
> +        }
en el caso de los inputs y labels que tengo, mas el span dentro de los labels, lleno el archivo de clases, ya que no tengo forma de poner cada elemento en divs separados para aplicarles las clases sin ponérselas a cada uno sin que me rompan la estructura por lo que no se si estaría bien hacer eso.

2021-09-13 23:49 UTC, Katherine-Damires commented on frontend/src/components/Login/Register.module.scss
> +position: absolute;
no encontre forma

2021-09-14 00:41 UTC, JhonAires-Anima commented on frontend/src/components/Login/Register.module.scss
> +        }
podes poner una misma clase a distintos elementos, no hay restricción en eso, sigue siendo html en el fondo

2021-09-14 00:42 UTC, JhonAires-Anima commented on frontend/src/components/Login/Register.module.scss
> +        }
además que podes poner varias clases a un elemento

2021-09-14 01:12 UTC, JhonAires-Anima requested changes

2021-09-14 01:12 UTC, JhonAires-Anima commented on frontend/src/components/Login/Register.module.scss
> +    background: rgba(0, 0, 0, .5)
El color debería ser en código `HEX`

2021-09-14 01:12 UTC, JhonAires-Anima commented on frontend/src/index.jsx
> +      <Register />
Recordá borrar esto

2021-09-14 01:12 UTC, JhonAires-Anima commented on frontend/src/components/Login/Register.module.scss
> +        margin-left: -5%;
por qué un margin negativo?

2021-09-14 01:16 UTC, Katherine-Damires commented on frontend/src/components/Login/Register.module.scss
> +        margin-left: -5%;
Por que le ajuste el width a mas de 100% y queda descentrado

2021-09-14 01:26 UTC, JhonAires-Anima commented on frontend/src/components/Login/Register.module.scss
> +    .tittle{
tiene doble `t`

2021-09-14 15:28 UTC, JhonAires-Anima approved these changes

2021-09-14 17:36 UTC, merged